<?php
return [
    'inicio' => 'Home',
    'servicios' => 'Services',
    'cuentas' => 'Accounts',
    'contacto' => 'Contact',
    'bienvenida' => 'Welcome to Your Digital Bank',
    'subtítulo' => 'Manage your finances easily and securely',
    'ir_cuentas' => 'Go to My Accounts',
    'acceder' => 'Access Account',
    'abrir_cuenta' => 'Open New Account',
    'operaciones' => 'Online Operations',
    'operaciones_desc' => 'Make deposits, withdrawals, and balance inquiries 24/7',
    'sucursales' => 'Branches',
    'sucursales_desc' => 'Find our network of branches nationwide',
    'historial' => 'Transaction History',
    'historial_desc' => 'Check and download your banking transactions',
    'Bienvenido' => 'Welcome',



    //formulario de register.view

    'nombre_completo' => 'Full Name',
    'correo' => 'Email',
    'teléfono' => 'Phone',
    'usuario' => 'Username',
    'contraseña' => 'Password',
    'confirmar_contraseña' => 'Confirm Password',
    'sucursal' => 'Preferred Branch',
    'acepto_términos' => 'I accept the Terms and Conditions',
    'registrarse' => 'Register',
    'inicia_sesión' => 'Log In',

    'footer_leyenda' => '<p>© 2025 BancoFassil - Systems Development I - UPDS - Bolivia</p><p> This is an educational project to simulate Banco Fassil\'s banking system for the Systems Development I course at UPDS. Banco Fassil is a real entity and you can visit its official website at <a href="http://www.fassil.com.bo/" target="_blank" class="text-white" >www.fassil.com.bo</a>.</p>',
    'footer_email' => 'info@bancofassil.com',
    'footer_teléfono' => '+591 12345678',
    'footer_privacidad' => 'Privacy Policy',
    'footer_términos' => 'Terms of Service',
    'mi_cuenta' => 'My Account',
    'cerrar_sesión' => 'Log Out',

    'lista_cuentas' => 'Account List',
    'crear_cuenta' => 'Create New Account',
    'cuenta_no_valida' => 'Invalid account type',
    'cuenta_creada' => 'Account created successfully',
    'cuenta_no_encontrada' => 'Account not found',
    'saldo_insuficiente' => 'Insufficient funds',
    'transferencia_realizada' => 'Transfer completed successfully',
    'tarjeta_creada' => 'Card created successfully',

    'error_nombre_invalido' => 'Invalid name',

    'credenciales_incorrectas' => 'Invalid credentials',
    'csrf_invalido' => 'Invalid CSRF token',
    'registro_exitoso' => 'Registration successful. You can now log in.',
    'error_registro' => 'Error registering user',
    'Registrarse' => 'Register',
    'Nombre Completo' => 'Full Name',
    'Correo Electrónico' => 'Email',
    'Teléfono' => 'Phone',
    'Usuario' => 'Username',
    'Contraseña' => 'Password',
    'Confirmar Contraseña' => 'Confirm Password',
    'Acepto los términos y condiciones' => 'I accept the terms and conditions',
    'Inicia sesión' => 'Log in',
    'Ya tienes una cuenta?' => 'Already have an account?',
    'Registro Exitoso' => 'Successful Registration',
    'Nombre Invalido' => 'Invalid name',
    'Email Invalido' => 'Invalid email',
    'Phone Invalido' => 'Invalid phone',
    'User Invalido' => 'Invalid username',
    'Password Invalido' => 'Invalid password',
    'Debes aceptar los términos y condiciones' => 'You must accept the terms and conditions',

    //lista de cuenta
    'Lista de Cuentas' => 'Account List',
    'Crear Nueva Cuenta' => 'Create New Account',
    'Cuenta creada correctamente' => 'Account created successfully',
    'Cuenta no encontrada' => 'Account not found',
    'Saldo insuficiente' => 'Insufficient balance',
    'Transferencia' => 'Transfer',
    'Transferencia de fondos' => 'Funds Transfer',
    'Transferencia realizada correctamente' => 'Transfer completed successfully',
    'Tarjeta creada correctamente' => 'Card created successfully',

    'crear_nueva_cuenta' => 'Create New Account',
    'tipo_de_cuenta' => 'Account Type',
    'seleccione_un_tipo' => 'Select an account type',
    'oficina_asociada' => 'Associated Office',
    'seleccione_una_oficina' => 'Select an office',

    'volver_lista_cuentas' => 'Back to account list',

    'error_404' => '404 - Page not found',
    'error_404_message' => 'Sorry, but the page you are looking for does not exist.',
    'volver_pagina_principal' => 'Back to the main page',
    //tarjeta para añadir fondo y quitar y trasaccion
    'balance' => 'Current Balance',
    'add_card' => 'Add Card',
    'make_transfer' => 'Make Transfer',
    'no_transactions' => 'No transactions recorded',
    'no_cards' => 'You don’t have any cards associated',
    'account' => 'Account',
    'current_balance' => 'Current Balance',


    'last_transactions' => 'Last Transactions',
    'card_number' => 'Card Number',
    'cvv' => 'CVV',
    'pin' => 'PIN',
    'expire' => 'Expires:',
    'deposit' => 'Deposit',
    'withdraw' => 'Withdraw',
    'add_funds' => 'Add funds to the account',
    'withdraw_funds' => 'Withdraw funds from the account',
    'confirm_transfer' => 'Confirm Transfer',
    'create_card' => 'Create Card',
    'card_type' => 'Card Type',
    'create_card_btn' => 'Create Card',
    'recent_transactions' => 'Recent Transactions',
    'associated_cards' => 'Associated Cards',
    'no_cards_associated' => 'You have no associated cards',
    'debit' => 'Debit',
    'expires' => 'Expires',
    'amount' => 'Amount',
    'transaction_type' => 'Transaction Type',
    'account_list' => 'Account List',
    'create_account' => 'Create New Account',
    'id' => 'ID',
    'description' => 'Description',
    'account_type' => 'Account Type',
    'status' => 'Status',
    'office' => 'Office',
    'actions' => 'Actions',
    'active' => 'Active',
    'inactive' => 'Inactive',
    'view' => 'View',
    'delete' => 'Delete',
    'no_accounts' => 'No accounts registered.',
    'Deposito' => 'Deposit',
    'Retiro' => 'Withdrawal',
    'Cuenta' => 'Account',
    'Cajero automático de Retiro' => 'ATM Withdrawal',
    'Compra en línea' => 'Buy online',
    'enabledForOnlinePurchases' => 'Enabled for online purchases',
    'enabled' => 'Enable',
    'disabled' => 'Disable',
    'name' => 'Name',
    'email' => 'Email',
    'phone' => 'Phone',
    'user' => 'User',
    'password' => 'Password',
    'type' => 'Type',
    'terms' => 'Terms',
    'officeId' => 'Office',
    'El monto supera el límite permitido' => 'The amount exceeds the allowed limit',
    'no_description' => 'No description',
    'administrar_cuentas' => 'Manage your bank accounts securely',
    'consultar_saldos' => 'Check balances',
    'cerrar_cuentas' => 'Close accounts',
    'realizar_transferencias' => 'Make transfers between accounts',
    'transacciones_seguras' => 'Secure transactions',
    'disponible_24_7' => 'Available 24/7',
    'administrar_tarjetas' => 'Manage your associated cards',
    'solicitar_tarjetas' => 'Request new cards',
    'activar_desactivar' => 'Activate/Deactivate',
    'control_compras_online' => 'Online purchase control',
    'servicios_adicionales' => 'Additional Services',
    'cajeros_automaticos' => 'ATMs',
    'tienda_virtual_desc' => 'Simulate purchases in our associated virtual store',
    'operaciones_protegidas' => 'All operations are protected with our banking security system.',
    'transferir_fondos' => 'Transfer funds',
    'gestionar_tarjetas' => 'Manage cards',
    'compra_en_línea' => 'Online purchase',
    'descripcion-meta' => "Simulation of Banco Fassil's banking system (Bolivia). Educational project for the Development of Systems I course at UPDS. Explore how an online bank would work.",
    'report_all_accounts' => 'All Accounts Report',
    'generate_report' => 'Generate Report',
    'all_accounts_report' => 'All Accounts Report',
    'generated_report' => 'Report generated',
    'transaction_history' => 'Transaction History',
    'Página' => 'Page',
    'de' => 'of',
    'Cuenta N° ' => 'Account N° ',
    'Saldo actual: ' => 'Current Balance: ',
    'Cliente: ' => 'Client: ',
    'Fecha de apertura: ' => 'Opening Date: ',
    'Tipo' => 'Type',
    'Descripción' => 'Description',
    'Fecha y Hora' => 'Date and Time',
    'Saldo Anterior' => 'Previous Balance',
    'Monto' => 'Amount',
    'Saldo Nuevo' => 'New Balance',
    'Desde: ' => 'To: ',
    'Hasta: ' => 'From: ',
    'Todo el historial' => 'All History',
    'generate'=> 'Generate',
    'cancel' => 'Cancel', 
    'generate_all_reports' => 'Generate all reports',
];
