<?php
return [
    'inicio' => 'Home',
    'servicios' => 'Services',
    'cuentas' => 'Accounts',
    'contacto' => 'Contact',
    'bienvenida' => 'Welcome to Your Digital Bank',
    'subtítulo' => 'Manage your finances easily and securely',
    'ir_cuentas' => 'Go to My Accounts',
    'acceder' => 'Access Account',
    'abrir_cuenta' => 'Open New Account',
    'operaciones' => 'Online Operations',
    'operaciones_desc' => 'Make deposits, withdrawals, and balance inquiries 24/7',
    'sucursales' => 'Branches',
    'sucursales_desc' => 'Find our network of branches nationwide',
    'historial' => 'Transaction History',
    'historial_desc' => 'Check and download your banking transactions',

    'nombre_completo' => 'Full Name',
    'correo' => 'Email',
    'teléfono' => 'Phone',
    'usuario' => 'Username',
    'contraseña' => 'Password',
    'confirmar_contraseña' => 'Confirm Password',
    'sucursal' => 'Preferred Branch',
    'acepto_términos' => 'I accept the Terms and Conditions',
    'registrarse' => 'Register',
    'inicia_sesión' => 'Log In',

    'footer_leyenda' => '© 2024 BancoFassil - Systems Development I',
    'footer_email' => 'info@bancofassil.com',
    'footer_teléfono' => '+591 12345678',
    'footer_privacidad' => 'Privacy Policy',
    'footer_términos' => 'Terms of Service',
    'mi_cuenta' => 'My Account',
    'cerrar_sesión' => 'Log Out',
];
