<?php
return [
    'inicio' => 'Inicio',
    'servicios' => 'Servicios',
    'cuentas' => 'Cuentas',
    'contacto' => 'Contacto',
    'bienvenida' => 'Bienvenido a Banco Fassil',
    'subtítulo' => 'Gestiona tus finanzas de manera fácil y segura',
    'ir_cuentas' => 'Ir a Mis Cuentas',
    'acceder' => 'Acceder a Cuenta',
    'abrir_cuenta' => 'Abrir Nueva Cuenta',
    'operaciones' => 'Operaciones en Línea',
    'operaciones_desc' => 'Realiza depósitos, retiros y consultas de saldo las 24 horas',
    'sucursales' => 'Sucursales',
    'sucursales_desc' => 'Encuentra nuestra red de agencias a nivel nacional',
    'historial' => 'Historial de Transacciones',
    'historial_desc' => 'Consulta y descarga tus movimientos bancarios',
    
    'nombre_completo' => 'Nombre Completo',
    'correo' => 'Correo Electrónico',
    'teléfono' => 'Teléfono',
    'usuario' => 'Usuario',
    'contraseña' => 'Contraseña',
    'confirmar_contraseña' => 'Confirmar Contraseña',
    'sucursal' => 'Sucursal Preferida',
    'acepto_términos' => 'Acepto los Términos y Condiciones',
    'registrarse' => 'Registrarse',
    'inicia_sesión' => 'Inicia Sesión',

    'footer_leyenda' => '© 2024 BancoFassil - Desarrollo de Sistemas I',
    'footer_email' => 'info@bancofassil.com',
    'footer_teléfono' => '+591 12345678',
    'footer_privacidad' => 'Política de Privacidad',
    'footer_términos' => 'Términos de Servicio',
    'mi_cuenta' => 'Mi Cuenta',
    'cerrar_sesión' => 'Cerrar Sesión',
];
