<?php
return [
    'inicio' => 'Inicio',
    'servicios' => 'Servicios',
    'cuentas' => 'Cuentas',
    'contacto' => 'Contacto',
    'bienvenida' => 'Bienvenido a Banco Fassil',
    'subtítulo' => 'Gestiona tus finanzas de manera fácil y segura',
    'ir_cuentas' => 'Ir a Mis Cuentas',
    'acceder' => 'Acceder a Cuenta',
    'abrir_cuenta' => 'Abrir Nueva Cuenta',
    'operaciones' => 'Operaciones en Línea',
    'operaciones_desc' => 'Realiza depósitos, retiros y consultas de saldo las 24 horas',
    'sucursales' => 'Sucursales',
    'sucursales_desc' => 'Encuentra nuestra red de agencias a nivel nacional',
    'historial' => 'Historial de Transacciones',
    'historial_desc' => 'Consulta y descarga tus movimientos bancarios',



    //formulario de register.view.php
    'nombre_completo' => 'Nombre Completo',
    'correo' => 'Correo Electrónico',
    'teléfono' => 'Teléfono',
    'usuario' => 'Usuario',
    'contraseña' => 'Contraseña',
    'confirmar_contraseña' => 'Confirmar Contraseña',
    'sucursal' => 'Sucursal Preferida',
    'acepto_términos' => 'Acepto los Términos y Condiciones',
    'registrarse' => 'Registrarse',
    'inicia_sesión' => 'Inicia Sesión',

    'footer_leyenda' => '© 2024 BancoFassil - Desarrollo de Sistemas I',
    'footer_email' => 'info@bancofassil.com',
    'footer_teléfono' => '+591 12345678',
    'footer_privacidad' => 'Política de Privacidad',
    'footer_términos' => 'Términos de Servicio',
    'mi_cuenta' => 'Mi Cuenta',
    'cerrar_sesión' => 'Cerrar Sesión',

    'lista_cuentas' => 'Lista de Cuentas',
    'crear_cuenta' => 'Crear Nueva Cuenta',
    'cuenta_no_valida' => 'Tipo de cuenta no válido',
    'cuenta_creada' => 'Cuenta creada correctamente',
    'cuenta_no_encontrada' => 'Cuenta no encontrada',
    'saldo_insuficiente' => 'Saldo insuficiente',
    'transferencia_realizada' => 'Transferencia realizada correctamente',
    'tarjeta_creada' => 'Tarjeta creada correctamente',

    'error_nombre_invalido' => 'Nombre inválido',
    'credenciales_incorrectas' => 'Credenciales incorrectas',
    'csrf_invalido' => 'Token CSRF inválido',
    'registro_exitoso' => 'Registro exitoso. Ahora puede iniciar sesión.',
    'error_registro' => 'Error al registrar el usuario',
    //lista de cuenta
    'Lista de Cuentas' => 'Lista de Cuentas',
    'Crear Nueva Cuenta' => 'Crear Nueva Cuenta',
    'Cuenta creada correctamente' => 'Cuenta creada correctamente',
    'Cuenta no encontrada' => 'Cuenta no encontrada',
    'Saldo insuficiente' => 'Saldo insuficiente',
    'Transferencia' => 'Transferencia',
    'Transferencia de fondos' => 'Transferencia de fondos',
    'Transferencia realizada correctamente' => 'Transferencia realizada correctamente',
    'Tarjeta creada correctamente' => 'Tarjeta creada correctamente',

    'crear_nueva_cuenta' => 'Crear Nueva Cuenta',
    'tipo_de_cuenta' => 'Tipo de Cuenta',
    'seleccione_un_tipo' => 'Seleccione un tipo de cuenta',
    'oficina_asociada' => 'Oficina Asociada',
    'seleccione_una_oficina' => 'Seleccione una oficina',
    'error_404' => '404 - Página no encontrada',
    'error_404_message' => 'Lo sentimos, pero la página que buscas no existe.',
    'volver_pagina_principal' => 'Volver a la página principal',
    'volver_lista_cuentas' => 'Volver a la lista de cuentas',

    //tarjeta para añadir fondo y quitar y trasaccion
    'balance' => 'Saldo actual',
    'add_card' => 'Agregar Tarjeta',
    'make_transfer' => 'Realizar Movimiento',
    'no_transactions' => 'No hay movimientos registrados',
    'no_cards' => 'No tienes tarjetas asociadas',

    'account' => 'Cuenta',
    'current_balance' => 'Saldo actual',

    'card_number' => 'Número de Tarjeta',
    'cvv' => 'CVV',
    'pin' => 'PIN',
    'expire' => 'Expira:',
    'deposit' => 'Depósito',
    'withdraw' => 'Retiro',
    'add_funds' => 'Añadir fondos a la cuenta',
    'withdraw_funds' => 'Retirar fondos de la cuenta',
    'confirm_transfer' => 'Confirmar Movimiento',
    'create_card' => 'Crear Tarjeta',
    'card_type' => 'Tipo de Tarjeta',
    'recent_transactions' => 'Últimos movimientos',
    'create_card_btn' => 'Crear Tarjeta',
    'associated_cards' => 'Tarjetas asociadas',
    'no_cards_associated' => 'No tienes tarjetas asociadas',
    'debit' => 'Débito',
    'credit' => 'Crédito',
    'amount' => 'Monto',
    'transaction_type' => 'Tipo de Movimiento',
    'expires' => 'Expira',
    'account_list' => 'Lista de Cuentas',
    'create_account' => 'Crear Nueva Cuenta',
    'id' => 'ID',
    'description' => 'Descripción',
    'account_type' => 'Tipo de Cuenta',
    'status' => 'Estado',
    'office' => 'Oficina',
    'actions' => 'Acciones',
    'active' => 'Activa',
    'inactive' => 'Inactiva',
    'view' => 'Ver',
    'delete' => 'Eliminar',
    'no_accounts' => 'No hay cuentas registradas.',
    'Deposito' => 'Deposito',
    'enabledForOnlinePurchases' => 'Habilitado para compras por internet',
    'enabled' => 'Habilitar',
    'disabled' => 'Deshabilitar',
    'name' => 'Nombre',
    'email' => 'Correo Electrónico',
    'phone' => 'Teléfono',
    'user' => 'Usuario',
    'password' => 'Contraseña',
    'type' => 'Tipo',
    'terms' => 'Términos',
    'officeId' => 'Oficina',
    'no_description' => 'Sin descripción',
];
